import { STATIONS, MATERIALS, DEFAULT_CONFIG, DEFAULT_LAYOUT, compilePlan, simulate, snapshot, makeRecipe, parseRecipe, makeFrameSTL } from './engine.js';
import { createFactoryScene } from './scene.js';

const $=id=>document.getElementById(id), copy=value=>JSON.parse(JSON.stringify(value));
const workbench=document.querySelector('.workbench');
const stockFor=n=>Object.fromEntries(MATERIALS.map(m=>[m.id,m.perCell*n]));
let config={...copy(DEFAULT_CONFIG),targetCells:20,reinvestEvery:3,stock:stockFor(20)},layout=copy(DEFAULT_LAYOUT),plan,result,time=0,playing=false,selected='integrate',factory=null,lastFrame=0,toastTimer;
let conditions='balanced',extraSerial=0,previousSummary=null;
let committedConfig=null,committedLayout=null;
const statusNames={pending:'입고 대기',blocked:'자재 부족',queued:'작업 대기',processing:'작업 중',complete:'출하 준비',commissioning:'공장 편입 중',installed:'공장 편입 완료',rejected:'검사 탈락'};
function clock(sec){const n=Math.floor(sec);return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200);}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`${name} 내보내기 완료`);}
function updateForm(){for(const id of['targetCells','reinvestEvery','seed'])$(id).value=config[id];$('duration').value=config.durationSec/60;}
function readForm(){return{...config,targetCells:Number($('targetCells').value),reinvestEvery:Number($('reinvestEvery').value),seed:Number($('seed').value),durationSec:Math.round(Number($('duration').value)*60)};}
function stageFor(id){return STATIONS.find(s=>s.id===(layout.find(p=>p.id===id)?.stationId||id))||STATIONS.find(s=>s.id===result?.resources.find(r=>`installed-${r.id}`===id)?.stationId);}
function stationRender(){const rows=layout.map((p,i)=>{const s=stageFor(p.id);return`<button class="station-item${p.id===selected?' selected':''}" data-station="${p.id}" aria-pressed="${p.id===selected}"><span class="station-number">${String(i+1).padStart(2,'0')}</span><span class="station-name">${s?.name||'조립 셀'}<small>${p.stationId?'ADDITIONAL RESOURCE':s?.kind==='printer'?'FIXTURE PRINTING':'ROBOT WORKCELL'}</small></span><span class="station-light"></span></button>`;});$('stationList').innerHTML=rows.join('');$('stationCount').textContent=`${layout.length} STATIONS`;}
function select(id){selected=id;const s=stageFor(id),p=layout.find(p=>p.id===id);$('selectedName').textContent=s?.name||'공장 편입 셀';$('selectedId').textContent=id.startsWith('installed-')?'NEW CELL':`S${String(Math.max(0,layout.findIndex(p=>p.id===id))+1).padStart(2,'0')}`;$('layoutX').value=p?.x??'';$('layoutZ').value=p?.z??'';$('moveStation').disabled=!p;$('layoutX').disabled=!p;$('layoutZ').disabled=!p;$('removeCell').disabled=!p?.stationId;$('selectedResource').textContent=id.startsWith('installed-')?'생산 완료 셀 편입':p?.stationId?'추가 조립 자원':'기본 공정 자원';stationRender();render();}
function rebuild({reset=true,message='계획이 컴파일되었습니다.'}={}){try{const c=readForm(),nextPlan=compilePlan(c),recipe=makeRecipe(nextPlan.config,layout),nextResult=simulate(recipe.config);plan=nextPlan;config=recipe.config;layout=recipe.layout;result=nextResult;committedConfig=copy(config);committedLayout=copy(layout);playing=false;if(reset)time=0;time=Math.min(time,result.durationSec);$('scrub').max=result.durationSec/60;document.querySelector('.timeline-ticks span:last-child').textContent=`${result.durationSec/60} min`;updateForm();const shorts=plan.shortages;$('planStatus').textContent=shorts.length?`부족 자재 ${shorts.length}종 · ${config.autoReplenish?'4분 후 공급 보충':'일부 생산 요청이 대기합니다.'}`:`${config.targetCells}대 생산 · ${plan.plannedReinvestment}대 공장 편입 계획`;factory?.setLayout(layout);stationRender();render();if(message)toast(message);return true;}catch(e){playing=false;if(committedConfig){config=copy(committedConfig);layout=copy(committedLayout);updateForm();if(!layout.some(p=>p.id===selected)&&!selected.startsWith('installed-'))selected='integrate';factory?.setLayout(layout);select(selected);}toast(e.message);$('planStatus').textContent=e.message;return false;}}
function render(){if(!result)return;const state=snapshot(result,time);factory?.update(state,selected);const counts=state.counts;$('completedValue').innerHTML=`${counts.completed} <em>/ ${config.targetCells}</em>`;$('installedValue').innerHTML=`${counts.installed} <em>대</em>`;$('resourcesValue').innerHTML=`${state.resources.length} <em>자원</em>`;$('timeValue').textContent=clock(time);$('scrub').value=time/60;$('scrub').style.setProperty('--progress',`${time/result.durationSec*100}%`);$('scrubLabel').textContent=`${(time/60).toFixed(1)} / ${result.durationSec/60}분`;$('play').textContent=playing?'Ⅱ':'▶';$('play').setAttribute('aria-label',playing?'시뮬레이션 일시정지':'시뮬레이션 시작');$('runState').textContent=playing?'생산 중':time===0?'준비됨':time>=result.durationSec?'실행 완료':'일시정지';$('runDetail').textContent=counts.blocked?`자재 부족 ${counts.blocked}대`:counts.rejected?`검사 탈락 ${counts.rejected}대`:`작업 중 ${counts.wip}대 · 출하 ${counts.shipped}대`;
 for(const button of document.querySelectorAll('[data-station]')){const s=stageFor(button.dataset.station);const rs=state.resources.filter(r=>r.stationId===s?.id);button.classList.toggle('busy',rs.some(r=>r.active));button.classList.toggle('blocked',s?.id==='receive'&&counts.blocked>0);}
 const selectedStage=stageFor(selected),selectedRes=selected.startsWith('installed-')?state.resources.filter(r=>`installed-${r.id}`===selected):selected.startsWith('manual-')?state.resources.filter(r=>r.id===selected):state.resources.filter(r=>r.id===`${selectedStage?.id}-01`),active=selectedRes.find(r=>r.active),queued=selectedRes[0]?.queue||0;$('selectedStatus').textContent=active?`셀 ${active.active.jobId} 작업 중 · ${Math.round(active.active.progress*100)}%`:queued?`${queued}대 작업 대기`:'대기';$('selectedDot').style.background=active?'#c7ab24':'#9baab2';
 $('bomList').innerHTML=MATERIALS.map(m=>`<div class="bom-row${state.stock[m.id]<m.perCell?' low':''}"><span>${m.name}</span><b>${state.stock[m.id]} <small>${m.unit}</small></b></div>`).join('');$('materialState').textContent=counts.blocked?'SUPPLY BLOCKED':'REMAINING';
 const events=state.events;$('logCount').textContent=`${events.length} EVENTS`;$('eventList').innerHTML=events.length?events.slice(-4).reverse().map(e=>`<li><time>${clock(e.time)}</time><span>${escapeHTML(e.message)}</span></li>`).join(''):'<li><time>00:00</time><span>생산 요청 대기 · 재생 버튼을 눌러 시작하세요.</span></li>';}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function scenario(name){conditions=name;const n=name==='expansion'?20:6;config={...copy(DEFAULT_CONFIG),targetCells:n,reinvestEvery:3,stock:stockFor(n),extraCells:layout.filter(p=>p.stationId).map(({id,stationId})=>({id,stationId}))};if(name==='shortage'){config.stock.joints=18;config.stock.controller=3;config.autoReplenish=false;}if(name==='testFailure'){config.forceTestFailure=true;config.testFailureRate=0;}updateForm();rebuild({message:name==='expansion'?'20대 연속 생산 계획을 불러왔습니다.':name==='balanced'?'6대 생산 계획을 불러왔습니다.':name==='shortage'?'자재 3대분 · 공급 부족 조건으로 다시 실행합니다.':'셀 2의 첫 검사 실패 · 재작업 경로를 적용했습니다.'});}
$('planForm').addEventListener('submit',e=>{e.preventDefault();rebuild();});$('preset').addEventListener('change',e=>scenario(e.target.value));
$('stationList').addEventListener('click',e=>{const b=e.target.closest('[data-station]');if(b)select(b.dataset.station);});
$('play').addEventListener('click',()=>{if(time>=result.durationSec)time=0;playing=!playing;render();});$('reset').addEventListener('click',()=>{time=0;playing=false;render();toast('같은 시드로 초기화했습니다.');});$('scrub').addEventListener('input',e=>{playing=false;time=Number(e.target.value)*60;render();});
$('moveStation').addEventListener('click',()=>{const p=layout.find(p=>p.id===selected),x=Number($('layoutX').value),z=Number($('layoutZ').value);if(!p)return;if(!$('layoutX').value.trim()||!$('layoutZ').value.trim()||!Number.isFinite(x)||!Number.isFinite(z)||Math.abs(x)>15||Math.abs(z)>15){toast('좌표는 -15m~15m 범위의 숫자를 입력하세요.');return;}p.x=x;p.z=z;committedLayout=copy(layout);factory?.setLayout(layout);render();toast(`${stageFor(selected)?.name} 좌표를 적용했습니다.`);});
$('addCell').addEventListener('click',()=>{const s=stageFor(selected);if(!s||['receive','print','pack'].includes(s.id)){toast('프레임·암·통합·툴·전자부·검사 중 추가할 공정을 선택하세요.');return;}const manual=layout.filter(p=>p.stationId).length;if(manual>=12){toast('추가 조립 셀은 최대 12대입니다.');return;}let id;do{id=`manual-${++extraSerial}`;}while(layout.some(p=>p.id===id));if(extraSerial>999){toast('추가 셀 ID 범위를 초과했습니다.');return;}layout.push({id,stationId:s.id,x:-6+(manual%4)*4,z:8+Math.floor(manual/4)*3});config.extraCells=[...(config.extraCells||[]),{id,stationId:s.id}];if(rebuild({message:'사전 구매한 조립 자원을 추가하고 생산 계획을 다시 계산했습니다.'}))select(id);});
$('removeCell').addEventListener('click',()=>{const p=layout.find(p=>p.id===selected);if(!p?.stationId)return;layout=layout.filter(p=>p.id!==selected);config.extraCells=(config.extraCells||[]).filter(p=>p.id!==selected);selected='integrate';rebuild({message:'추가 조립 자원을 삭제했습니다.'});select(selected);});
$('injectTest').addEventListener('click',()=>{const previous={config:copy(result.config),summary:copy(result.summary)};config.forceTestFailure=true;config.testFailureRate=0;if(rebuild({message:'첫 검사 실패 조건을 적용해 처음부터 다시 실행합니다.'})){previousSummary=previous;playing=true;}});
$('injectSupply').addEventListener('click',()=>{const previous={config:copy(result.config),summary:copy(result.summary)};config.stock={...config.stock,joints:6,controller:1};config.autoReplenish=false;if(rebuild({message:'1대분 자재 조건을 적용해 처음부터 다시 실행합니다.'})){previousSummary=previous;playing=true;}});
$('recover').addEventListener('click',()=>{config.autoReplenish=true;config.forceTestFailure=false;if(rebuild({message:'4분 후 부족 자재 보충 조건으로 다시 실행합니다. 검사 실패는 재작업 경로로 복구됩니다.'}))playing=true;});
$('exportRecipe').addEventListener('click',()=>{try{download('cellforge-recipe.json',JSON.stringify(makeRecipe(config,layout),null,2));}catch(e){toast(e.message);}});$('exportFrame').addEventListener('click',()=>download('cellforge-frame.stl',makeFrameSTL({width:3,depth:2.4,height:3.2,beam:.1}),'model/stl'));$('exportResults').addEventListener('click',()=>download('cellforge-results.json',JSON.stringify({model:'CELLFORGE / Level 1',currentTime:time,current:snapshot(result,time),result,comparison:previousSummary?{previous:previousSummary,current:{config,summary:result.summary}}:null},null,2)));
$('importButton').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const recipe=parseRecipe(await file.text());config=recipe.config;layout=recipe.layout;extraSerial=Math.max(0,...layout.map(p=>Number(p.id.replace('manual-',''))||0));updateForm();selected='integrate';rebuild({message:'설계를 불러왔습니다. 저장된 조건으로 재실행할 수 있습니다.'});select(selected);}catch(error){toast(`불러오기 실패: ${error.message}`);}e.target.value='';});
$('ghostButton').addEventListener('click',()=>{const v=$('ghostButton').getAttribute('aria-pressed')!=='true';$('ghostButton').setAttribute('aria-pressed',String(v));$('ghostButton').classList.toggle('active',v);factory?.setGhost(v);});
for(const[button,mode]of[['isoView','iso'],['topView','top'],['fitView','iso']])$(button).addEventListener('click',()=>{factory?.setView(mode);$('isoView').classList.toggle('active',mode==='iso');$('topView').classList.toggle('active',mode==='top');});
document.querySelectorAll('[data-panel]').forEach(button=>button.addEventListener('click',()=>{workbench.dataset.panel=button.dataset.panel;document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b===button));}));
try{factory=createFactoryScene($('scene'),{onSelect:select});}catch(error){$('sceneError').hidden=false;$('sceneError').textContent='이 브라우저에서 3D 화면을 열 수 없습니다. WebGL을 지원하는 브라우저에서 다시 여세요. 생산 계획, 시뮬레이션과 내보내기는 계속 사용할 수 있습니다.';console.error(error);}
$('duration').min=2;$('duration').max=120;$('duration').step='any';$('seed').min=0;$('seed').max=4294967295;$('reinvestEvery').max=10;$('targetCells').min=2;for(const id of['layoutX','layoutZ']){$(id).min=-15;$(id).max=15;}updateForm();stationRender();rebuild({message:''});select(selected);
let lastUIFrame=0;
function tick(now){const delta=Math.min((now-lastFrame)/1000,.25);lastFrame=now;if(playing&&result){time=Math.min(result.durationSec,time+delta*Number($('speed').value));if(time>=result.durationSec){playing=false;toast(`완성 ${result.summary.completed}대 · 공장 편입 ${result.summary.installed}대 · 실행 완료`);render();}else if(now-lastUIFrame>=100){lastUIFrame=now;render();}else factory?.update(snapshot(result,time),selected);}requestAnimationFrame(tick);}requestAnimationFrame(tick);


