import * as THREE from './vendor/three.module.js';
import { OrbitControls } from './vendor/OrbitControls.js';
import { STATIONS } from './engine.js';

// All geometry is generated locally; the arms follow the scheduled resource state.
export function createFactoryScene(container, { onSelect = () => {} } = {}) {
 const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false });
 renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap;
 renderer.setClearColor(0xe6ebed); renderer.outputColorSpace = THREE.SRGBColorSpace; container.appendChild(renderer.domElement);
 const scene = new THREE.Scene(); scene.fog = new THREE.Fog(0xe6ebed, 30, 65);
 const camera = new THREE.PerspectiveCamera(37, 1, 0.1, 300); camera.position.set(20, 21, 24);
 const controls = new OrbitControls(camera, renderer.domElement); controls.target.set(0, 1, 1); controls.enableDamping = true; controls.dampingFactor=.08; controls.maxPolarAngle = Math.PI / 2.12; controls.minDistance = 8; controls.maxDistance = 220;
 let managedCamera=true,viewMode='iso';
 controls.addEventListener('start',()=>{managedCamera=false;});
 scene.add(new THREE.HemisphereLight(0xffffff,0x82949e,2.3));
 const light = new THREE.DirectionalLight(0xfffdf5,3); light.position.set(-12,24,14);light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.camera.left=-21;light.shadow.camera.right=21;light.shadow.camera.top=20;light.shadow.camera.bottom=-20;light.shadow.bias=-.0003; scene.add(light);
 const fill=new THREE.DirectionalLight(0xffffff,1.4);fill.position.set(15,7,-12);scene.add(fill);
 const mats={frame:new THREE.MeshStandardMaterial({color:0x283137,metalness:.8,roughness:.35}),edge:new THREE.MeshStandardMaterial({color:0x869398,metalness:.9,roughness:.35}),white:new THREE.MeshStandardMaterial({color:0xeef0ef,metalness:.25,roughness:.35}),yellow:new THREE.MeshStandardMaterial({color:0xf0cb2c,metalness:.35,roughness:.38}),black:new THREE.MeshStandardMaterial({color:0x404a50,metalness:.5,roughness:.45}),floor:new THREE.MeshStandardMaterial({color:0xd8e0e3,roughness:.83}),roller:new THREE.MeshStandardMaterial({color:0xa8b5bb,metalness:.85,roughness:.29}),green:new THREE.MeshStandardMaterial({color:0x57ad8a,emissive:0x284d39,emissiveIntensity:.2}),red:new THREE.MeshStandardMaterial({color:0xc45c47}),pcb:new THREE.MeshStandardMaterial({color:0x3f786e,roughness:.6}),pallet:new THREE.MeshStandardMaterial({color:0xb3a382,roughness:.8}),ghost:new THREE.MeshStandardMaterial({color:0xe5c329,transparent:true,opacity:.2,depthWrite:false})};
 const geo={}; const unitBox=new THREE.BoxGeometry(1,1,1);
 function box(g,x,y,z,w,h,d,mat=mats.frame){const m=new THREE.Mesh(unitBox,mat);m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
 function cylinder(g,x,y,z,r,h,mat=mats.edge,axis='y',r2=r){const key=`${r}:${r2}:${h}`;geo[key]??=new THREE.CylinderGeometry(r2,r,h,16);const m=new THREE.Mesh(geo[key],mat);m.position.set(x,y,z);if(axis==='x')m.rotation.z=Math.PI/2;if(axis==='z')m.rotation.x=Math.PI/2;m.castShadow=true;g.add(m);return m;}
 function beam(g,x,y,z,w,h,d){box(g,x,y,z,w,h,d);const smallest=Math.min(w,h,d);if(h>w&&h>d){box(g,x+.051,y,z,w*.12,h,.006,mats.edge);box(g,x,y,z+.051,.006,h,d*.12,mats.edge);}else if(w>h){box(g,x,y+.051,z,w,.006,d*.14,mats.edge);}else{box(g,x,y+.051,z,w*.14,.006,d,mats.edge);}}
 function textSprite(text,color='#42565f',scale=1){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.font='600 31px Arial,"Malgun Gothic"';ctx.textAlign='center';ctx.fillText(text,256,53);const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tx,depthTest:false,transparent:true}));s.scale.set(3.8*scale,.72*scale,1);return s;}
 function cable(g,points,color=0x383f42,r=.023){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,20,r,5,false),new THREE.MeshStandardMaterial({color,roughness:.75}));g.add(mesh);return mesh;}
 const floor=box(scene,0,-.14,0,34,.25,26,mats.floor);floor.receiveShadow=true;
 const grid=new THREE.GridHelper(34,34,0xbcc9cf,0xcbd5da);grid.position.y=.001;scene.add(grid);
 // Safety stripes and aisle define the occupied engineering floor.
 for(let x=-13;x<14;x+=.55){const stripe=box(scene,x,.011,8.65,.27,.012,.24,mats.yellow);stripe.rotation.y=-Math.PI/5;}
 for(let z=-10;z<9;z+=.55){box(scene,-13,.011,z,.13,.012,.3,mats.yellow);box(scene,13,.011,z,.13,.012,.3,mats.yellow);}
 const floorLabel=textSprite('CELLFORGE / ASSEMBLY FLOOR', '#96a6af',2);floorLabel.position.set(0,.04,9.6);floorLabel.material.depthTest=true;floorLabel.rotation.x=-Math.PI/2;scene.add(floorLabel);
 const conveyor=new THREE.Group(); scene.add(conveyor);const rollers=[];const movingParts=[];
 function conveyorRun(cx,cz,len,rotate=false){const g=new THREE.Group();g.position.set(cx,0,cz);if(rotate)g.rotation.y=Math.PI/2;conveyor.add(g);box(g,0,.64,0,len,.12,1.08,mats.black);for(const z of[-.51,.51])beam(g,0,.87,z,len,.09,.09);for(let x=-len/2+.2;x<len/2;x+=.32){const r=cylinder(g,x,.79,0,.1,.96,mats.roller,'z');rollers.push(r);}for(let x=-len/2+.4;x<=len/2;x+=2){for(const z of[-.4,.4])beam(g,x,.33,z,.08,.65,.08);}for(const x of[-len/2,len/2])box(g,x,.83,0,.1,.05,1.1,mats.yellow);}
 conveyorRun(0,-1.8,18);conveyorRun(0,1.8,18);conveyorRun(9,0,3.6,true);
 for(let i=0;i<7;i++){const g=new THREE.Group();box(g,0,.88,0,.63,.06,.7,mats.black);box(g,0,1.01,0,.38,.2,.45,i%3===0?mats.white:mats.pallet);box(g,0,1.12,0,.27,.025,.34,mats.edge);conveyor.add(g);movingParts.push(g);}
 const cells=new Map(),pickables=[];let selected='integrate',ghostVisible=false,currentSnapshot=null,layout=[];
 const ghostRoot=new THREE.Group();ghostRoot.visible=false;scene.add(ghostRoot);
 function robot(parent,x=0,z=0,small=false){const root=new THREE.Group();root.position.set(x,.91,z);root.scale.setScalar(small?.66:1);parent.add(root);cylinder(root,0,0,0,.28,.14,mats.black);cylinder(root,0,.12,0,.21,.2,mats.white);const yaw=new THREE.Group();root.add(yaw);cylinder(yaw,0,.32,0,.17,.25,mats.white);const shoulder=new THREE.Group();shoulder.position.y=.4;yaw.add(shoulder);cylinder(shoulder,0,0,0,.19,.38,mats.black,'z');cylinder(shoulder,0,0,.2,.13,.025,mats.yellow,'z');box(shoulder,0,.44,0,.22,.88,.25,mats.white);box(shoulder,.115,.44,0,.01,.6,.08,mats.edge);const elbow=new THREE.Group();elbow.position.y=.88;shoulder.add(elbow);cylinder(elbow,0,0,0,.15,.31,mats.black,'z');cylinder(elbow,0,0,.165,.095,.027,mats.yellow,'z');box(elbow,0,.37,0,.18,.74,.2,mats.white);const wrist=new THREE.Group();wrist.position.y=.75;elbow.add(wrist);cylinder(wrist,0,0,0,.115,.25,mats.black,'z');box(wrist,0,.19,0,.14,.37,.16,mats.white);const tool=new THREE.Group();tool.position.y=.39;wrist.add(tool);cylinder(tool,0,0,0,.1,.15,mats.yellow);box(tool,-.09,.14,0,.055,.2,.08,mats.black);box(tool,.09,.14,0,.055,.2,.08,mats.black);box(tool,0,.035,0,.24,.07,.12,mats.yellow);cable(shoulder,[[.13,.05,-.15],[.2,.35,-.19],[.17,.78,-.16]],0x2f3a40,.024);cable(elbow,[[.1,.06,-.13],[.15,.32,-.13],[.1,.73,-.12]],0x2f3a40,.022);shoulder.rotation.z=-.52;elbow.rotation.z=-1.6;wrist.rotation.z=-.6;return{root,yaw,shoulder,elbow,wrist,tool};}
 function tray(parent,x,z){box(parent,x,.96,z,.65,.075,.53,mats.black);for(let i=0;i<4;i++){box(parent,x-.22+i*.145,1.035,z,.095,.08,.32,mats.edge);cylinder(parent,x-.22+i*.145,1.12,z,.047,.09,mats.yellow);}}
 function cabinet(g){box(g,1.08,.7,.75,.4,1.35,.45,mats.white);box(g,1.08,.75,.987,.33,1.13,.02,mats.edge);box(g,1.08,1.02,1.005,.23,.2,.015,mats.black);box(g,1.08,1.02,1.018,.19,.14,.01,mats.pcb);for(let j=0;j<6;j++)box(g,1.08,.33+j*.065,1.005,.26,.013,.01,mats.black);cylinder(g,.95,.78,1.02,.025,.014,mats.yellow,'z');cable(g,[[.89,.12,.75],[.67,.07,.95],[.3,.08,.96],[0,.9,.7]],0x313b42,.03);}
 function makeCell(station,id,position,extra=false){const g=new THREE.Group();g.position.set(position.x,0,position.z);scene.add(g);const flip=position.z<0?Math.PI:0;g.rotation.y=flip;
 const base=box(g,0,.025,0,3.12,.04,2.4,new THREE.MeshStandardMaterial({color:extra?0xcbd9d5:0xd0dade,roughness:.75}));base.userData.cellId=id;pickables.push(base);
 const highlight=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(3.15,.08,2.44)),new THREE.LineBasicMaterial({color:0xd8b524,transparent:true,opacity:1}));highlight.position.y=.08;highlight.visible=false;g.add(highlight);
 for(const x of[-1.4,1.4])for(const z of[-1,1]){beam(g,x,1.62,z,.1,3.24,.1);box(g,x,.1,z,.22,.09,.22,mats.black);cylinder(g,x,3.25,z,.09,.05,mats.edge);}
 for(const z of[-1,1])beam(g,0,3.18,z,2.9,.1,.1);for(const x of[-1.4,1.4])beam(g,x,3.18,0,.1,.1,2.1);
 // Work surface and modular fixture rail.
 box(g,0,.87,0,2.58,.085,1.68,mats.edge);box(g,0,.924,0,2.47,.026,1.6,mats.black);for(const x of[-1.2,1.2])for(const z of[-.7,.7])beam(g,x,.43,z,.08,.84,.08);
 for(let x=-1.13;x<=1.13;x+=.2)box(g,x,.945,.43,.05,.015,.6,mats.edge);
 const arm=robot(g,-.43,-.15,station.id==='print');tray(g,.52,.3);cabinet(g);
 let mechanism=null;
 if(station.id==='receive'||station.id==='pack'){for(let i=0;i<3;i++){box(g,.4+i*.23,1.14,-.5,.2,.36,.31,mats.pallet);box(g,.4+i*.23,1.325,-.5,.2,.012,.05,mats.yellow);}box(g,-.45,.17,1.25,1.5,.2,.72,mats.pallet);for(let i=0;i<4;i++)box(g,-1+i*.37,.3,1.25,.28,.08,.72,mats.pallet);}
 if(station.id==='frame'){for(const x of[.25,.85])for(const z of[-.6,0])beam(g,x,1.31,z,.055,.7,.055);beam(g,.55,1.66,-.6,.65,.055,.055);beam(g,.55,1.66,0,.65,.055,.055);beam(g,.25,1.66,-.3,.055,.055,.65);beam(g,.85,1.66,-.3,.055,.055,.65);}
 if(station.id==='print'){for(let i=0;i<2;i++){const p=new THREE.Group();p.position.set(-.45+i*1.15,0,0);g.add(p);box(p,0,1.02,0,.85,.14,.75,mats.black);for(const x of[-.35,.35])beam(p,x,1.52,-.28,.05,.95,.05);beam(p,0,1.98,-.28,.78,.05,.05);beam(p,0,1.65,-.23,.72,.04,.04);box(p,0,1.62,-.1,.12,.16,.15,mats.yellow);cylinder(p,.44,1.72,-.28,.2,.12,mats.black,'z');box(p,0,1.12,0,.3,.15,.3,mats.yellow);}arm.root.visible=false;}
 if(station.id==='arm'){for(let i=0;i<3;i++){cylinder(g,.2+i*.3,1.09,-.5,.095,.22,mats.white);cylinder(g,.2+i*.3,1.22,-.5,.08,.05,mats.yellow);}robot(g,.6,.2,true);}
 if(station.id==='integrate'){beam(g,0,3.01,0,2.6,.12,.14);const hoist=new THREE.Group();hoist.position.set(.55,2.8,0);g.add(hoist);box(hoist,0,0,0,.4,.3,.4,mats.yellow);cylinder(hoist,0,-.37,0,.017,.6,mats.black);box(hoist,0,-.7,0,.19,.05,.19,mats.yellow);mechanism=hoist;robot(g,.65,.25,true);}
 if(station.id==='tool'){box(g,.6,1.05,-.36,.7,.18,.5,mats.white);for(let i=0;i<3;i++){box(g,.35+i*.24,1.18,-.36,.16,.1,.28,mats.yellow);box(g,.35+i*.24,1.27,-.36,.04,.1,.12,mats.black);}}
 if(station.id==='electronics'){for(let i=0;i<2;i++){box(g,.43,1.08,-.35+i*.5,.65,.05,.37,mats.pcb);for(let j=0;j<4;j++)box(g,.2+j*.13,1.12,-.35+i*.5,.07,.04,.15,mats.black);}cable(g,[[.2,1.02,-.5],[.7,1.04,-.7],[.9,1.03,-.1]],0xe7bb26,.012);}
 if(station.id==='test'){const hoop=new THREE.Group();g.add(hoop);for(const x of[.1,1])beam(hoop,x,1.7,-.4,.06,1.6,.06);beam(hoop,.55,2.49,-.4,1,.06,.06);box(hoop,.55,2.35,-.4,.22,.16,.22,mats.black);box(hoop,.55,2.26,-.4,.09,.02,.09,mats.yellow);}
 cylinder(g,1.35,3.47,1,.045,.12,mats.green);cylinder(g,1.35,3.6,1,.045,.12,mats.yellow);cylinder(g,1.35,3.73,1,.045,.12,mats.red);
 const plaque=new THREE.Group();plaque.position.set(-.9,2.89,1.06);g.add(plaque);box(plaque,0,0,0,.85,.28,.025,mats.black);const label=textSprite(`${STATIONS.findIndex(s=>s.id===station.id)+1}`,'#f1ce36',.4);label.position.set(0,0,.03);plaque.add(label);
 const name=textSprite((extra?'＋ ':'')+station.name,extra?'#518675':'#4f626c',.8);name.position.set(position.x,.05,position.z+(position.z<0?-1.6:1.6));scene.add(name);
 return{g,base,highlight,arm,mechanism,name,stationId:station.id,id,extra};}
 function disposeCell(c){scene.remove(c.g,c.name);const index=pickables.indexOf(c.base);if(index!==-1)pickables.splice(index,1);const sharedMaterials=new Set(Object.values(mats)),sharedGeometry=new Set([unitBox,...Object.values(geo)]),disposedGeometry=new Set(),disposedMaterials=new Set(),disposedTextures=new Set();for(const root of[c.g,c.name])root.traverse(node=>{if(node.geometry&&!sharedGeometry.has(node.geometry)&&!disposedGeometry.has(node.geometry)){node.geometry.dispose();disposedGeometry.add(node.geometry);}for(const material of(Array.isArray(node.material)?node.material:[node.material])){if(!material||sharedMaterials.has(material)||disposedMaterials.has(material))continue;if(material.map&&!disposedTextures.has(material.map)){material.map.dispose();disposedTextures.add(material.map);}material.dispose();disposedMaterials.add(material);}});}
 function clearCells(){for(const c of cells.values())disposeCell(c);cells.clear();pickables.length=0;while(ghostRoot.children.length)ghostRoot.remove(ghostRoot.children[0]);}
 function setLayout(next){layout=next.map(p=>({...p}));clearCells();for(const p of layout){const s=STATIONS.find(s=>s.id===(p.stationId||p.id))||STATIONS.find(s=>s.id==='integrate');cells.set(p.id,makeCell(s,p.id,p,Boolean(p.extra||!STATIONS.some(s=>s.id===p.id))));}for(let i=0;i<3;i++){const gx=-5+i*4;box(ghostRoot,gx,.04,9.1,3,.07,2.3,mats.ghost);for(const x of[-1.4,1.4])for(const z of[-1,1])box(ghostRoot,gx+x,1.6,9.1+z,.08,3.2,.08,mats.ghost);box(ghostRoot,gx,3.2,9.1,2.9,.08,2.1,mats.ghost);}if(currentSnapshot)update(currentSnapshot,selected);if(managedCamera)fitCamera();}
 function update(snapshot,selectedId=selected){currentSnapshot=snapshot;selected=selectedId;let boundsChanged=false;const resources=snapshot?.resources||[];for(const r of resources.filter(r=>r.sourceJobId!==null&&r.sourceJobId!==undefined)){const id=`installed-${r.id}`;if(!cells.has(id)){const s=STATIONS.find(s=>s.id===r.stationId);if(s){const extras=[...cells.values()].filter(c=>c.extra).length;const position={x:-6+(extras%4)*4,z:8+(Math.floor(extras/4)*3)};cells.set(id,makeCell(s,id,position,true));boundsChanged=true;}}}
 for(const[id,c]of[...cells]){if(id.startsWith('installed-')&&!resources.some(r=>`installed-${r.id}`===id)){disposeCell(c);cells.delete(id);boundsChanged=true;continue;}c.highlight.visible=id===selected;const r=id.startsWith('installed-')?resources.find(r=>`installed-${r.id}`===id):id.startsWith('manual-')?resources.find(r=>r.id===id):resources.find(r=>r.stationId===c.stationId&&r.sourceJobId===null&&!r.id.startsWith('manual-'));const p=r?.active?.progress??0;const active=Boolean(r?.active);c.arm.yaw.rotation.y=active?Math.sin(p*Math.PI*2)*.65:.25;c.arm.shoulder.rotation.z=-.45-(active?Math.sin(p*Math.PI)*.5:0);c.arm.elbow.rotation.z=-1.65+(active?Math.sin(p*Math.PI*2)*.55:0);c.arm.wrist.rotation.z=-.65-(active?Math.cos(p*Math.PI*2)*.4:0);c.arm.tool.rotation.y=p*Math.PI*2;if(c.mechanism)c.mechanism.position.y=2.8-(active?Math.sin(p*Math.PI)*.45:0);}
 const t=snapshot?.time||0;rollers.forEach(r=>r.rotation.z=t*.7);const jobs=(snapshot?.jobs||[]).filter(j=>['processing','queued','complete','commissioning'].includes(j.status));movingParts.forEach((p,i)=>{const job=jobs[i];p.visible=Boolean(job);if(!job)return;const stage=STATIONS.find(s=>s.id===job.stageId)||STATIONS[STATIONS.length-1],installed=cells.get(`installed-${job.resourceId}`),position=installed?installed.g.position:(layout.find(p=>p.id===job.resourceId)||layout.find(p=>p.id===stage.id)||stage);p.position.set(position.x+(job.progress||0)*.35,0,position.z+(position.z<0?2.4:-2.4));});if(boundsChanged&&managedCamera)fitCamera();}
 let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const rect=renderer.domElement.getBoundingClientRect();const point=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);const ray=new THREE.Raycaster();ray.setFromCamera(point,camera);const hits=ray.intersectObjects(pickables);if(hits[0])onSelect(hits[0].object.userData.cellId);});
 // Project all factory-bound corners onto the chosen camera axes. Fit both
 // horizontal and vertical FOV; portrait screens are limited by horizontal FOV.
 function fitCamera(){const bounds=new THREE.Box3(new THREE.Vector3(-9.6,0,-5.9),new THREE.Vector3(9.6,4,5.9));for(const c of cells.values())bounds.expandByObject(c.g);const center=bounds.getCenter(new THREE.Vector3()),baseFactory=cells.size<=STATIONS.length&&bounds.min.x>=-10&&bounds.max.x<=10&&bounds.min.z>=-6&&bounds.max.z<=6;const target=baseFactory?new THREE.Vector3(0,viewMode==='top'?0:1,viewMode==='top'?0:1):new THREE.Vector3(center.x,viewMode==='top'?0:1,center.z);const direction=(viewMode==='top'?new THREE.Vector3(0,1,.0007):new THREE.Vector3(20,20,23)).normalize(),right=new THREE.Vector3().crossVectors(camera.up,direction).normalize(),up=new THREE.Vector3().crossVectors(direction,right).normalize();const tanV=Math.tan(THREE.MathUtils.degToRad(camera.fov/2)),tanH=tanV*Math.max(.1,camera.aspect);let distance=viewMode==='top'?29:Math.sqrt(20*20+20*20+23*23);for(const x of[bounds.min.x,bounds.max.x])for(const y of[bounds.min.y,bounds.max.y])for(const z of[bounds.min.z,bounds.max.z]){const relative=new THREE.Vector3(x,y,z).sub(target);distance=Math.max(distance,relative.dot(direction)+Math.max(Math.abs(relative.dot(right))/tanH,Math.abs(relative.dot(up))/tanV)*1.15);}controls.target.copy(target);camera.position.copy(target).addScaledVector(direction,distance);controls.maxDistance=Math.max(220,distance*2);camera.far=Math.max(300,distance+150);scene.fog.near=Math.max(30,distance*.9);scene.fog.far=Math.max(65,distance+50);camera.updateProjectionMatrix();controls.update();}
 const resize=()=>{const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();if(managedCamera)fitCamera();};const observer=new ResizeObserver(resize);observer.observe(container);resize();let alive=true;function draw(){if(!alive)return;controls.update();renderer.render(scene,camera);requestAnimationFrame(draw);}draw();
 function setView(mode){viewMode=mode==='top'?'top':'iso';managedCamera=true;fitCamera();}
 return{setLayout,update,setGhost(v){ghostVisible=v;ghostRoot.visible=v;},setView,dispose(){alive=false;observer.disconnect();clearCells();controls.dispose();renderer.dispose();container.replaceChildren();}};
}
